image: ghcr.io/gmeligio/flutter-android:3.44.8

stages:
  - build
  - deploy

build_web:
  stage: build
  when: manual
  script:
    - cd example
    - flutter --version
    - flutter config --enable-web
    - flutter pub get
    - flutter build web --release --base-href "/$CI_PROJECT_NAME/"
  artifacts:
    paths:
      - example/build/web

pages:
  stage: deploy
  when: manual
  needs:
    - job: build_web
      artifacts: true
  script:
    - cp -r example/build/web public
  artifacts:
    paths:
      - public
  pages: true